# Generated by Django 6.1 on 2026-08-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_complaintdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('SUMMONS', 'Summons'), ('NOTICE', 'Notice'), ('ENFORCEMENT', 'Enforcement Notice'), ('PENALTY', 'Penalty Notice')], max_length=20)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHYSICAL', 'Physical Delivery'), ('POSTAL', 'Postal Service'), ('OTHER', 'Other')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='complaints.complaint')),
            ],
        ),
    ]
