# Generated by Django 6.1 on 2026-08-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
        ('complaints', '0002_complaintdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_responses', to='complaints.complaint')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='case_management.complaintnotice')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='complaints.respondent')),
            ],
        ),
    ]
