# Generated by Django 6.1 on 2026-08-17 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_respondentresponse'),
        ('complaints', '0002_complaintdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('settlement_agreement', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_sessions', to='complaints.complaint')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
