# Generated by Django 6.1 on 2026-08-17 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_hearing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaired_hearing_committees', to=settings.AUTH_USER_MODEL)),
                ('hearing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='case_management.hearing')),
                ('member_three', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='third_hearing_committee_memberships', to=settings.AUTH_USER_MODEL)),
                ('member_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_hearing_committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
