# Generated by Django 6.1 on 2026-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0005_hearingcommittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearingcommittee',
            name='chairperson_expertise',
            field=models.CharField(blank=True, choices=[('LAW', 'Law'), ('DATA_PROTECTION', 'Personal Data Protection'), ('ICT', 'Information and Communication Technology'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hearingcommittee',
            name='member_three_expertise',
            field=models.CharField(blank=True, choices=[('LAW', 'Law'), ('DATA_PROTECTION', 'Personal Data Protection'), ('ICT', 'Information and Communication Technology'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hearingcommittee',
            name='member_two_expertise',
            field=models.CharField(blank=True, choices=[('LAW', 'Law'), ('DATA_PROTECTION', 'Personal Data Protection'), ('ICT', 'Information and Communication Technology'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
