# Generated by Django 6.1 on 2026-08-17 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_hearingcommittee_chairperson_expertise_and_more'),
        ('complaints', '0002_complaintdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('decision_date', models.DateField()),
                ('outcome', models.CharField(choices=[('COMPLAINT_ALLOWED', 'Complaint Allowed'), ('COMPLAINT_DISMISSED', 'Complaint Dismissed'), ('PARTIALLY_ALLOWED', 'Complaint Partially Allowed'), ('SETTLED', 'Settled'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('UNDER_REVIEW', 'Under Review'), ('FINAL', 'Final'), ('ENFORCEMENT', 'Under Enforcement'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('findings', models.TextField()),
                ('orders', models.TextField(blank=True)),
                ('reasons', models.TextField(blank=True)),
                ('award_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('costs_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_award', to='complaints.complaint')),
                ('hearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_awards', to='case_management.hearing')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_decision_awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
