# Generated by Django 6.1 on 2026-08-17 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0007_decisionaward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('grounds', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Review Approved'), ('REJECTED', 'Review Rejected'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Award Confirmed'), ('VARIED', 'Award Varied'), ('REVERSED', 'Award Reversed')], default='PENDING', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('decision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_reviews', to=settings.AUTH_USER_MODEL)),
                ('decision_award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='case_management.decisionaward')),
            ],
        ),
    ]
