# Generated by Django 6.1 on 2026-08-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0008_awardreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnforcementCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement_reference', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('compliance_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOTICE_ISSUED', 'Notice Issued'), ('COMPLIANCE_PENDING', 'Compliance Pending'), ('COMPLIED', 'Complied'), ('NON_COMPLIANT', 'Non-Compliant'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('enforcement_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enforcement_cases', to='case_management.decisionaward')),
            ],
        ),
    ]
