# Generated by Django 6.1 on 2026-08-17 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0009_enforcementcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostTaxation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_reference', models.CharField(max_length=50, unique=True)),
                ('filing_date', models.DateField()),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_allowed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_TAXATION', 'Under Taxation'), ('TAXED', 'Taxed'), ('DISALLOWED', 'Disallowed'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('taxation_date', models.DateField(blank=True, null=True)),
                ('taxation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_taxations', to=settings.AUTH_USER_MODEL)),
                ('decision_award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_taxations', to='case_management.decisionaward')),
            ],
        ),
    ]
