# Generated by Django 6.1 on 2026-08-17 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0010_costtaxation'),
        ('complaints', '0002_complaintdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_reference', models.CharField(max_length=50, unique=True)),
                ('closure_date', models.DateField()),
                ('reason', models.CharField(choices=[('AWARD_COMPLIED', 'Award Complied With'), ('SETTLEMENT_REACHED', 'Settlement Reached'), ('REVIEW_COMPLETED', 'Review Completed'), ('ENFORCEMENT_COMPLETED', 'Enforcement Completed'), ('OTHER', 'Other')], max_length=40)),
                ('summary', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_cases', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closure', to='complaints.complaint')),
            ],
        ),
    ]
